version: '3'

services:
  setup_db:
    build:
      context: .
    ports:
      - "8529:8529"
    env_file:
      - '.env'
    volumes:
      - "../../volumes/arangodb:/var/lib/arangodb3"
      - "../../volumes/arangodb-apps:/var/lib/arangodb3-apps"
